variables:
  IMAGE: rwthos/gi4

stages:
  - prepare
  - build

# Stage: prepare
##############################################################################

docker:
  stage: prepare
  script:
    - docker build -t ${IMAGE} -f docker/Dockerfile .
  tags:
    - shell
    - linux

# Stage: build
##############################################################################

build:
  stage: build
  script:
    - make
  image: ${IMAGE}
  tags:
    - docker
